with open('input.txt', 'r') as f:
    a=list(eval(f.readline()))
    b=sorted(a)
    c=a
    c.sort(reverse=True)
    d=len(a)
    e=max(a)
    f=min(a)
    g=a+[111]
with open ('output.txt','w') as f:
    f.write('lista initiala: ')
    f.write(str(a))
    f.write('\n')
    f.write('lista sortata crescator: ')
    f.write(str(b))
    f.write('\n')
    f.write('lista sortata descrescator: ')
    f.write(str(c))
    f.write('\n')
    f.write('numarul elementelor este: ')
    f.write(str(d))
    f.write('\n')
    f.write('elementul maxim este: ')
    f.write(str(e))
    f.write('\n')
    f.write('elementul minim este: ')
    f.write(str(f))
    f.write('\n')
    f.write(str(g))
